### ISSUE TITLE
Should we time-out half closed connections?

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-tcp.spec#14]
To avoid resource leaks, after output is ended, TCP Nukleus should reset input stream if it is not ended after a certain time.  To verify this, test case https://github.com/reaktivity/nukleus-tcp.spec/blob/develop/src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.close/server/target.rpt should expect to receive an END frame on the target input sometime after the END is written to target output established..

**Comment by jfallows** [comment]
Should this be the responsibility of the `tcp` nukleus directly, or some upstream nukleus that wishes control the timeout at a higher protocol level?

**Comment by jfallows** [comment]
We now rely on the half-open approach to properly flush data still buffered in one direction even when the opposite direction has (half-)closed.
